export const RESOLVE_ROUTE_START = 'RESOLVE_ROUTE_START'
export const RESOLVE_ROUTE_END = 'RESOLVE_ROUTE_END'
export const RESOLVED_ON_SERVER = 'RESOLVED_ON_SERVER'
export const RESOLVE_KEEP = 'RESOLVE_KEEP'