export const RESOLVE_ROUTE_START = 'RESOLVE_ROUTE_START'
export const RESOLVE_ROUTE_END = 'RESOLVE_ROUTE_END'
export const RESOLVE_SAGA_START = 'RESOLVE_SAGA_START'
export const RESOLVE_SAGA_END = 'RESOLVE_SAGA_END'
export const RESOLVED_ON_SERVER = 'RESOLVED_ON_SERVER'
export const RESOLVE_KEEP = 'RESOLVE_KEEP'
export const RESOLVE_SET_PREV_PATH = 'RESOLVE_SET_PREV_PATH'

export const RESOLVE_RELOAD = 'RESOLVE_RELOAD'
